//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sear.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Input", Namespace="http://config.soap.it")]
    [System.SerializableAttribute()]
    public partial class Input : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Sear.ServiceReference1.ArrayOf_xsd_int vectorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Sear.ServiceReference1.ArrayOf_xsd_int vector {
            get {
                return this.vectorField;
            }
            set {
                if ((object.ReferenceEquals(this.vectorField, value) != true)) {
                    this.vectorField = value;
                    this.RaisePropertyChanged("vector");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOf_xsd_int", Namespace="http://config.soap.it", ItemName="item")]
    [System.SerializableAttribute()]
    public class ArrayOf_xsd_int : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Output", Namespace="http://config.soap.it")]
    [System.SerializableAttribute()]
    public partial class Output : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Sear.ServiceReference1.ArrayOf_xsd_int sortedVectorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Sear.ServiceReference1.ArrayOf_xsd_int sortedVector {
            get {
                return this.sortedVectorField;
            }
            set {
                if ((object.ReferenceEquals(this.sortedVectorField, value) != true)) {
                    this.sortedVectorField = value;
                    this.RaisePropertyChanged("sortedVector");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://config.soap.it", ConfigurationName="ServiceReference1.MyService")]
    public interface MyService {
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento input dallo spazio dei nomi http://config.soap.it non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Sear.ServiceReference1.sortResponse sort(Sear.ServiceReference1.sortRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Sear.ServiceReference1.sortResponse> sortAsync(Sear.ServiceReference1.sortRequest request);
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento username dallo spazio dei nomi http://config.soap.it non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Sear.ServiceReference1.echoResponse echo(Sear.ServiceReference1.echoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Sear.ServiceReference1.echoResponse> echoAsync(Sear.ServiceReference1.echoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sortRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sort", Namespace="http://config.soap.it", Order=0)]
        public Sear.ServiceReference1.sortRequestBody Body;
        
        public sortRequest() {
        }
        
        public sortRequest(Sear.ServiceReference1.sortRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://config.soap.it")]
    public partial class sortRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Sear.ServiceReference1.Input input;
        
        public sortRequestBody() {
        }
        
        public sortRequestBody(Sear.ServiceReference1.Input input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sortResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sortResponse", Namespace="http://config.soap.it", Order=0)]
        public Sear.ServiceReference1.sortResponseBody Body;
        
        public sortResponse() {
        }
        
        public sortResponse(Sear.ServiceReference1.sortResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://config.soap.it")]
    public partial class sortResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Sear.ServiceReference1.Output sortReturn;
        
        public sortResponseBody() {
        }
        
        public sortResponseBody(Sear.ServiceReference1.Output sortReturn) {
            this.sortReturn = sortReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class echoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="echo", Namespace="http://config.soap.it", Order=0)]
        public Sear.ServiceReference1.echoRequestBody Body;
        
        public echoRequest() {
        }
        
        public echoRequest(Sear.ServiceReference1.echoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://config.soap.it")]
    public partial class echoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public echoRequestBody() {
        }
        
        public echoRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class echoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="echoResponse", Namespace="http://config.soap.it", Order=0)]
        public Sear.ServiceReference1.echoResponseBody Body;
        
        public echoResponse() {
        }
        
        public echoResponse(Sear.ServiceReference1.echoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://config.soap.it")]
    public partial class echoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int echoReturn;
        
        public echoResponseBody() {
        }
        
        public echoResponseBody(int echoReturn) {
            this.echoReturn = echoReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyServiceChannel : Sear.ServiceReference1.MyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServiceClient : System.ServiceModel.ClientBase<Sear.ServiceReference1.MyService>, Sear.ServiceReference1.MyService {
        
        public MyServiceClient() {
        }
        
        public MyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sear.ServiceReference1.sortResponse Sear.ServiceReference1.MyService.sort(Sear.ServiceReference1.sortRequest request) {
            return base.Channel.sort(request);
        }
        
        public Sear.ServiceReference1.Output sort(Sear.ServiceReference1.Input input) {
            Sear.ServiceReference1.sortRequest inValue = new Sear.ServiceReference1.sortRequest();
            inValue.Body = new Sear.ServiceReference1.sortRequestBody();
            inValue.Body.input = input;
            Sear.ServiceReference1.sortResponse retVal = ((Sear.ServiceReference1.MyService)(this)).sort(inValue);
            return retVal.Body.sortReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sear.ServiceReference1.sortResponse> Sear.ServiceReference1.MyService.sortAsync(Sear.ServiceReference1.sortRequest request) {
            return base.Channel.sortAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sear.ServiceReference1.sortResponse> sortAsync(Sear.ServiceReference1.Input input) {
            Sear.ServiceReference1.sortRequest inValue = new Sear.ServiceReference1.sortRequest();
            inValue.Body = new Sear.ServiceReference1.sortRequestBody();
            inValue.Body.input = input;
            return ((Sear.ServiceReference1.MyService)(this)).sortAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sear.ServiceReference1.echoResponse Sear.ServiceReference1.MyService.echo(Sear.ServiceReference1.echoRequest request) {
            return base.Channel.echo(request);
        }
        
        public int echo(string username, string password) {
            Sear.ServiceReference1.echoRequest inValue = new Sear.ServiceReference1.echoRequest();
            inValue.Body = new Sear.ServiceReference1.echoRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Sear.ServiceReference1.echoResponse retVal = ((Sear.ServiceReference1.MyService)(this)).echo(inValue);
            return retVal.Body.echoReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sear.ServiceReference1.echoResponse> Sear.ServiceReference1.MyService.echoAsync(Sear.ServiceReference1.echoRequest request) {
            return base.Channel.echoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sear.ServiceReference1.echoResponse> echoAsync(string username, string password) {
            Sear.ServiceReference1.echoRequest inValue = new Sear.ServiceReference1.echoRequest();
            inValue.Body = new Sear.ServiceReference1.echoRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Sear.ServiceReference1.MyService)(this)).echoAsync(inValue);
        }
    }
}
